version: '3.7'

services:
    backend:
        build:
          context: ./simple-api-student-main
          dockerfile: Dockerfile
        container_name: mybackend
        networks:
        - app-network
        depends_on:
        - database

    database:
        build:
          context : .
          dockerfile : Dockerfile
        container_name: mydatabase
        networks:
        - app-network

    httpd:
        build:
          context : ./httpserver
          dockerfile : Dockerfile
        container_name: myfrontend
        ports:
        - "8080:80"
        networks:
        - app-network
        depends_on:
        - backend

networks:
    app-network:
